<?php

return [
    'driver' => env('FLEXMIND_CURRENCY_RATE_DRIVER', 'european-central-bank'),
    'drivers' => [
        'albania',
        'armenia',
        'australia',
        'azerbaijan',
        'bceao',
        'belarus',
        'bosnia-and-herzegovina',
        'botswana',
        'bulgaria',
        'canada',
        'china',
        'croatia',
        'czech-republic',
        'denmark',
        'england',
        'european-central-bank',
        'fiji',
        'georgia',
        'hungary',
        'iceland',
        'israel',
        'macedonia',
        'moldavia',
        'norway',
        'poland',
        'romania',
        'russia',
        'serbia',
        'sweden',
        'switzerland',
        'turkey',
        'ukraine',
    ],
    'table-name' => env('FLEXMIND_CURRENCY_RATE_TABLENAME', 'currency_rates'),
    'retry' => [
        'count' => env('FLEXMIND_CURRENCY_RATE_RETRY_COUNT', 3),
        'sleep' => env('FLEXMIND_CURRENCY_RATE_RETRY_SLEEP', 1000),
        'factor' => env('FLEXMIND_CURRENCY_RATE_RETRY_FACTOR', 2),
    ],
];
